[package]
name = "borderpatrol-terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.2"
nn = "0.1.6"
rand = "0.8.5"

[[bin]]
name = "borderpatrol-terminal"

